"""Add tag model and opportunity_tags association table

Revision ID: b3900cc964e4
Revises: 80e71076a6b9
Create Date: 2025-09-03 10:10:45.535801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3900cc964e4'
down_revision = '80e71076a6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('opportunity_tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'opportunity_id')
    )
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmark_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_opportunity_approved_by_id'), ['approved_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_opportunity_approved_by_id', 'user', ['approved_by_id'], ['id'])
        batch_op.drop_column('tags')
        batch_op.drop_column('approved_by')

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reaction_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_reported_opportunity_id'), ['reported_opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_reported_user_id'), ['reported_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_reporter_id'), ['reporter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_report_reported_user_id'))
        batch_op.drop_index(batch_op.f('ix_report_reported_opportunity_id'))

    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_reaction_opportunity_id'))

    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_opportunity_approved_by_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_opportunity_user_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_approved_by_id'))
        batch_op.drop_column('approved_by_id')

    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookmark_opportunity_id'))

    op.drop_table('opportunity_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
