"""Add password_hash to User table~

Revision ID: e3ec228198ff
Revises: 
Create Date: 2025-07-12 22:47:41.048877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ec228198ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('pasword_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pasword_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
